# Generated by Django 6.0.1 on 2026-02-15 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_number', models.IntegerField(help_text='Car number, e.g. 1 for Verstappen, 44 for Hamilton', unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('name_acronym', models.CharField(help_text='e.g. "VER", "HAM", "NOR"', max_length=3)),
                ('team_name', models.CharField(max_length=100)),
                ('team_colour', models.CharField(help_text='Hex color, e.g. "#3671C6"', max_length=7)),
                ('headshot_url', models.URLField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Currently competing in the championship')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['driver_number'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.IntegerField(db_index=True, help_text='OpenF1 session identifier', unique=True)),
                ('meeting_key', models.IntegerField(db_index=True, help_text='OpenF1 Grand Prix identifier')),
                ('session_name', models.CharField(help_text='e.g. "Race", "Qualifying", "Practice 1"', max_length=50)),
                ('session_type', models.CharField(choices=[('practice', 'Practice'), ('qualifying', 'Qualifying'), ('sprint', 'Sprint'), ('race', 'Race')], max_length=10)),
                ('circuit_name', models.CharField(max_length=100)),
                ('circuit_short_name', models.CharField(max_length=20)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-3', max_length=3)),
                ('date_start', models.DateTimeField(db_index=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('is_live', models.BooleanField(default=False, help_text='Session currently in progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('threat_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force'), ('SQL_INJECTION', 'SQL Injection'), ('XSS', 'Cross-Site Scripting'), ('RATE_LIMIT', 'Rate Limit'), ('INVALID_TOKEN', 'Invalid Token'), ('SUSPICIOUS_PATTERN', 'Suspicious Pattern'), ('DATA_EXFIL', 'Data Exfiltration'), ('PARAMETER_TAMPERING', 'Parameter Tampering')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('description', models.TextField()),
                ('raw_request', models.JSONField(help_text='Sanitized request data, no sensitive information')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RaceControlMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('category', models.CharField(help_text='e.g. "Flag", "SafetyCar", "Penalty"', max_length=50)),
                ('message', models.TextField(help_text='Full message text')),
                ('flag', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('DOUBLE_YELLOW', 'Double Yellow'), ('RED', 'Red'), ('BLUE', 'Blue'), ('BLACK', 'Black'), ('BLACK_WHITE', 'Black and White'), ('CHEQUERED', 'Chequered')], max_length=20)),
                ('driver_number', models.IntegerField(blank=True, help_text='The driver the message concerns, if any', null=True)),
                ('lap_number', models.IntegerField(blank=True, null=True)),
                ('sector', models.IntegerField(blank=True, help_text='1, 2, or 3', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_messages', to='f1_pitwall.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PitStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lap_number', models.IntegerField(help_text='The lap on which the pit stop occurred')),
                ('pit_duration', models.FloatField(help_text='Time stationary in pit box, seconds')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='f1_pitwall.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='f1_pitwall.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stint_number', models.IntegerField(help_text='1 for first stint, 2 after first pit, etc.')),
                ('compound', models.CharField(choices=[('SOFT', 'Soft'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('INTERMEDIATE', 'Intermediate'), ('WET', 'Wet')], max_length=15)),
                ('tyre_age_at_start', models.IntegerField(default=0, help_text='Non-zero if starting on used tires')),
                ('lap_start', models.IntegerField()),
                ('lap_end', models.IntegerField(blank=True, help_text='Null if stint is in progress', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stints', to='f1_pitwall.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stints', to='f1_pitwall.session')),
            ],
            options={
                'ordering': ['stint_number'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('air_temperature', models.FloatField(help_text='Degrees Celsius')),
                ('track_temperature', models.FloatField(help_text='Degrees Celsius')),
                ('humidity', models.FloatField(help_text='Percentage, 0-100')),
                ('wind_speed', models.FloatField(help_text='Meters per second')),
                ('wind_direction', models.IntegerField(help_text='Degrees, 0-360')),
                ('rainfall', models.BooleanField(default=False)),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure in millibars', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='f1_pitwall.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(help_text='e.g. "GET", "POST", "WS"', max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.FloatField()),
                ('request_body_hash', models.CharField(blank=True, help_text='SHA-256 hash, not the actual body', max_length=64)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('threat_indicators', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous requests', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f1_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='idx_audit_ip_timestamp'), models.Index(fields=['is_suspicious', 'timestamp'], name='idx_audit_suspicious_ts')],
            },
        ),
        migrations.CreateModel(
            name='LapData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lap_number', models.IntegerField()),
                ('lap_duration', models.FloatField(blank=True, help_text='Total lap time in seconds, null for incomplete laps', null=True)),
                ('sector_1', models.FloatField(blank=True, help_text='Sector 1 time in seconds', null=True)),
                ('sector_2', models.FloatField(blank=True, help_text='Sector 2 time in seconds', null=True)),
                ('sector_3', models.FloatField(blank=True, help_text='Sector 3 time in seconds', null=True)),
                ('speed_trap', models.FloatField(blank=True, help_text='Speed at the speed trap in km/h', null=True)),
                ('is_pit_out_lap', models.BooleanField(default=False)),
                ('is_pit_in_lap', models.BooleanField(default=False)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='f1_pitwall.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='f1_pitwall.session')),
            ],
            options={
                'ordering': ['lap_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'driver', 'lap_number'), name='uq_lap_session_driver_number')],
            },
        ),
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed', models.IntegerField(help_text='km/h, range 0-370')),
                ('rpm', models.IntegerField(help_text='Engine RPM, range 0-15000')),
                ('throttle', models.IntegerField(help_text='0-100 percentage')),
                ('brake', models.IntegerField(help_text='0-100 percentage')),
                ('gear', models.IntegerField(help_text='0 for neutral, 1-8')),
                ('drs', models.IntegerField(help_text='DRS status code from OpenF1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='f1_pitwall.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='f1_pitwall.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'driver', 'timestamp'], name='idx_telem_sess_drv_ts')],
            },
        ),
    ]
