# Generated by Django 6.0.1 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_pitwall', '0002_f1userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='data_source',
            field=models.CharField(
                default='openf1_car_data',
                help_text='Source marker: openf1_car_data or fallback_lap_speed_trap',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
