# Generated by Django 6.0.1 on 2026-02-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.CharField(max_length=20)),
                ('db_size', models.CharField(max_length=50)),
                ('media_size', models.CharField(max_length=50)),
                ('disk_total', models.CharField(max_length=50)),
                ('disk_used', models.CharField(max_length=50)),
                ('disk_available', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Server Statistics',
                'verbose_name_plural': 'Server Statistics',
                'ordering': ['-collected_at'],
            },
        ),
    ]
